### ISSUE TITLE
** (FunctionClauseError) no function clause matching in JSONPointer.walk_container/7 

### ISSUE THREAD

**Issue by dderooy** [odogono/elixir-jsonpointer#7]
The following code 
```
data = Jason.decode!(~s({"one":1,"two":2,"array":[1,2,3], "dict":{"four": "4", "five": "5"}}))
JSONPointer.get( data, "/array/0/1" )
```
returns:
** (FunctionClauseError) no function clause matching in JSONPointer.walk_container/7  

Can it be updated to return an error tuple? something like:
```
{:error, "no function clause matching"}
```

<img width="938" alt="Screen Shot 2022-12-19 at 7 21 01 PM" src="https://user-images.githubusercontent.com/30082592/208552926-0e22dc62-d1cf-4a58-beaf-1a616398fdc5.png">

nice library btw

**Comment by odogono** [comment]
Have fixed and added a test case in the latest release

the return value in that case will be {:error, "key not found: /1"}

thank you!
